name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build
        run: mvn compile

      - name: Package
        run: mvn package

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.3-openjdk-17
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Test
        run: mvn test

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
